import json
from typing import Any, Dict, List

import pandas as pd
import streamlit as st

from config import Config
from database.db_manager import DatabaseManager


st.title("⚖️ HRBA Insights — Saved Justifications")

st.markdown(
    """
    View saved HRBA analyses and justifications generated by the HRBA matcher
    (spaCy or Ollama). Use filters to narrow by document or date and export results.
    """
)

db = DatabaseManager()
org_id = st.session_state.get("org_id") if "org_id" in st.session_state else db.get_or_create_organisation("Default Organisation")

# Fetch documents for organisation
docs = db.fetchall(
    "SELECT id, title FROM documents WHERE organisation_id = ? ORDER BY created_at DESC",
    (org_id,),
)
doc_map = {d["id"] if isinstance(d, dict) else d[0]: (d["title"] if isinstance(d, dict) else d[1]) for d in docs}

doc_options = ["All documents"] + [f"{doc_id}: {title}" for doc_id, title in doc_map.items()]
selected_doc = st.selectbox("Filter by document", options=doc_options)

# Build query
params: List[Any] = [org_id]
query = (
    "SELECT sa.id, sa.document_id, d.title AS doc_title, sa.model_used, sa.full_response_json, sa.created_at "
    "FROM semantic_analyses sa JOIN documents d ON d.id = sa.document_id "
    "WHERE d.organisation_id = ? "
    "ORDER BY sa.created_at DESC"
)

rows = db.fetchall(query, tuple(params))

records: List[Dict[str, Any]] = []
for r in rows:
    sa_id = r.get("id") if isinstance(r, dict) else r[0]
    doc_id = r.get("document_id") if isinstance(r, dict) else r[1]
    doc_title = r.get("doc_title") if isinstance(r, dict) else r[2]
    model_used = r.get("model_used") if isinstance(r, dict) else r[3]
    raw = r.get("full_response_json") if isinstance(r, dict) else r[4]
    created_at = r.get("created_at") if isinstance(r, dict) else r[5]

    # Normalize raw JSON
    parsed = None
    if not raw:
        parsed = []
    else:
        if isinstance(raw, (dict, list)):
            parsed = raw
        else:
            try:
                parsed = json.loads(raw)
            except Exception:
                # try to extract JSON substring
                text = str(raw)
                s = text.find("{")
                e = text.rfind("}")
                if s != -1 and e != -1 and e > s:
                    try:
                        parsed = json.loads(text[s : e + 1])
                    except Exception:
                        parsed = []
                else:
                    parsed = []

    # parsed can be dict or list; normalize to list of entries
    entries = []
    if isinstance(parsed, dict):
        entries = [parsed]
    elif isinstance(parsed, list):
        entries = parsed

    for ent in entries:
        if not isinstance(ent, dict):
            continue
        # Determine highest scoring category if present
        scores = {k: ent.get(k) for k in ("availability", "accessibility", "acceptability", "quality") if ent.get(k) is not None}
        if scores:
            highest = max(scores.items(), key=lambda x: float(x[1]))
            highest_category, highest_score = highest[0], float(highest[1])
        else:
            highest_category, highest_score = None, None

        justification = ent.get("justification") or ent.get("reason") or ent.get("explanation")
        original_text = ent.get("original_text") or ent.get("text") or ""

        records.append(
            {
                "analysis_id": sa_id,
                "document_id": doc_id,
                "document_title": doc_title,
                "model_used": model_used,
                "created_at": created_at,
                "original_text": original_text,
                "highest_category": highest_category,
                "highest_score": highest_score,
                "justification": justification,
                "raw_json": json.dumps(ent, ensure_ascii=False),
            }
        )

# Apply document filter
if selected_doc != "All documents":
    sel_id = int(selected_doc.split(":", 1)[0])
    records = [r for r in records if int(r["document_id"]) == sel_id]

if not records:
    st.info("No saved HRBA analyses found for the selected filters.")
else:
    df = pd.DataFrame(records)
    st.subheader(f"Saved Justifications ({len(df)})")
    st.dataframe(df[["created_at", "document_id", "document_title", "model_used", "highest_category", "highest_score", "justification"]])

    csv = df.to_csv(index=False).encode("utf-8")
    st.download_button("Export CSV", csv, file_name="hrba_justifications.csv", mime="text/csv")

    st.markdown("---")
    st.subheader("Raw entries")
    for row in records:
        with st.expander(f"Doc {row['document_id']} — {row['highest_category']} — {row['created_at']}"):
            st.write(row["original_text"])
            st.write("Justification:")
            st.write(row.get("justification"))
            st.markdown("**Raw JSON**")
            st.json(json.loads(row["raw_json"]) if row["raw_json"] else {})
